Django/djangonautic/accounts/urls.py
from . import views
from django.urls import path, re_path
from django.conf.urls import url

app_name ='accounts'

urlpatterns = [
    path('signup/', views.signup_view, name = 'signup'),
    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
    ]

Django/djangonautic/articles/urls.py
from . import views
from django.urls import path, re_path

app_name = 'articles'

urlpatterns = [
    path('',views.article_list,name ='list'),
    path('create/',views.article_create,name ='create'),
    re_path('(?P<slug>[\w-]+)/$', views.article_detail, name ='detail'),

]

Django/djangonautic/djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/',views.about),
    path('',views.homepage),
    path('accounts/',include('accounts.urls')),
    path('articles/',include('articles.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Django/djangonautic/accounts/models.py
from django.db import models

# Create your models here.

Django/djangonautic/articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
	title = models.CharField(max_length = 100)
	slug = models.SlugField()
	body = models.TextField()
	date = models.DateField() 
	thumb= models.ImageField(default='default.png',blank=True)
	#add thumbnail and author later

	def __str__(self):
		return self.title 

	def snippet(self):
		return self.body[:50]+'...'

Django/djangonautic/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view (request):
	if request.method == 'POST':
		form=UserCreationForm(request.POST)
		if form.is_valid():
			user =form.save()
			login(request,user)
			# login the user
			return redirect('articles:list')
	else:
		 form = UserCreationForm()
	return render(request,'accounts/signup.html',{'form':form})

def login_view (request):
	if request.method == 'POST':
		form=AuthenticationForm(data=request.POST)
		if form.is_valid():
			# login the user
			user =form.get_user()
			login(request,user)
			if 'next' in request.POST:
				return redirect(request.POST.get('next'))
			else: 
				return redirect('articles:list')

	else:
		form=AuthenticationForm()

	return render(request,'accounts/login.html',{'form':form})

def logout_view (request):
	if request.method=='POST':
		logout(request)
		return redirect('articles:list')

Django/djangonautic/articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

def article_list(request):
	articles= Article.objects.all().order_by('date')
	return render(request,'articles/list.html',{'articles':articles})

def article_detail(request,slug):
	article = Article.objects.get(slug=slug)
	return render(request,'articles/article_detail.html',{'article':article})

@login_required(login_url="/accounts/login/")
def article_create (request):
	 return render(request,'articles/article_create.html')

Django/djangonautic/djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):
	#return HttpResponse('Homepage')
	return render(request,'homepage.html')

def about(request):
	#return HttpResponse('about')
	return render(request,'about.html')

Django/djangonautic/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}

 <h1>Login</h1>
 <form class="site-form" action="{% url 'accounts:login' %}" method="post">
 	{% csrf_token %}
 	{{ form }}
 	{% if request.GET.next%}
 	<input type="hidden" name="next" value="{{ request.GET.next  }}">
 	{% endif %}
 	<input type="submit" value="Login">
 </form>

{%  endblock %}  

Django/djangonautic/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}

 <h1>signup</h1>
 <form class="site-form" action="/accounts/signup/" method="post">
 	{% csrf_token %}
 	{{ form }}
 	<input type="submit" value="Signup">
 </form>

{%  endblock %} 

Django/djangonautic/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="create-article">
	<h2>Create An Awesome New article</h2>
</div>
 

{%  endblock %} 

Django/djangonautic/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="article-detail">
	<div class="article">
		<img src="{{ article.thumb.url}}">
		<h2>{{article.title}}</h2>
		<p>{{article.body}}</p>
		<p>{{article.date}}</p>
		
	</div>
	
</div>

{%  endblock %} 

Django/djangonautic/articles/templates/articles/list.html
{% extends 'base_layout.html' %}

{% block content %}

<h1>Article List</h1>
<div class='articles'>
	{% for article in articles %}
	<div class='articles'>
		<h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
		<p>{{ article.snippet }}</p>
		<p>{{ article.date }}</p>
	</div>
	{%endfor%}
</div>

{%  endblock %} 

Django/djangonautic/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Article List</title>
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu" />
	<link rel="stylesheet" type="text/css" href="{% static 'styles.css'%}">


</head>
<body>
	<header class="wrapper">
		<h1><a href="{% url 'articles:list'%}"><img src="{% static 'logo.png' %}" alt="DjangoNautic"></a></h1>
		<nav>
			<ul>
				<li>
					 <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
					 	{%csrf_token%}
					 	<button type="submit">Logout</button>
					 </form>
				</li>
			</ul>
		</nav>

	</header>

<div class="wrapper">
	{% block content %}
	{% endblock%}
</div>


</body>
</html> 